version: '3.9'

services:
  neo4j:
    image: neo4j:5.5.0
    container_name: server1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - /.data
      - /.logs
      - ./datamart_csv:/var/lib/neo4j/import
      - ./plugins:/plugins
    restart: always